name: Build and Deploy Gatsby

on:
  push:

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm ci --legacy-peer-deps
    - run: npm install -g gatsby-cli@5.13.2
    - run: gatsby build
    - run: ls -al public
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/deploy_key
        sudo chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H "${{ secrets.HOST }}" > ~/.ssh/known_hosts
      
    - name: SFTP upload
      run: sftp -i ~/.ssh/deploy_key ${{ secrets.USER }}@${{ secrets.HOST }} <<< $'cd site/html \n put -r public/*'
